env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
settings:
  react:
    version: detect
plugins:
  - react
  - "no-floating-promise"
rules:
  {
    "@typescript-eslint/no-floating-promises": "off",
    "react/react-in-jsx-scope": "off",
    "@typescript-eslint/triple-slash-reference": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/space-before-function-paren": "off",
    generator-star-spacing: "off",
    "@typescript-eslint/semi": [2, "always"],
    "@typescript-eslint/member-delimiter-style": "off",
    "semi": "off",
  }
