version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: web
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    command: yarn start
    environment:
      - NODE_ENV=development
      - PORT=3000